### PR TITLE
[Performance]: optimize loading time

### PR DESCRIPTION
**Pull request by princ3od**
Hi @umechanhika,
I just added some optimizations for the use case when using dotted_line as a normal line (dashGapLength = 0), and also changed Wrap to ListView.builder. 
Thank you for creating this useful package!

### CODE REVIEW

**Comment by umechanhika** [comment]
@princ3od 
Thank you for your contribute!
I am very happy to hear the voices of the users.
Looking at your proposal, I have some comments, so I will add them from now on.

**Comment by umechanhika** [comment]
@princ3od 

> I just added some optimizations for the use case when using dotted_line as a normal line (dashGapLength = 0)

Returning the Container when dashGapLength is 0 is very rational and I agree.
How much improvement will you see in loading time by doing this?
If you have any measurement results with a measurement tool, please let me know.

**Comment by umechanhika** [comment]
@princ3od 

> and also changed Wrap to ListView.builder.

I implemented it using ListView in older versions.
However, when I used ListView for the internal implementation of dotted_line, I found that the performance when drawing dotted_line in ListView was very bad, so I changed to use Wrap instead of ListView.

Just in case, I tried running a sample code that displays a lot of dotted_line in a ListView on a physical device (Pixel 3) with `flutter run --profile` in order to see if changing to ListView actually affects performance.

As a result, the performance at the time of scrolling is about 60fps in the implementation using Wrap, while it is about 25fps in the implementation using ListView.

I'm sorry for your suggestion, but I can't accept this suggestion for the above reasons.

**Comment by princ3od** [comment]
Thank you for reviewing my PR.
Actually, I used the package wrong to show a normal line. Silly me.
But like when you set `dashLength` to a very small value (below 1 for example), it may cause lag. Because the number of `dash` is countless, and also be double since we render `dashGap` too.
I suggest that we only render `dash` when `dashGapColor` is transparent, and only render 1 `dash` line with many `dashGap` when `dashGapColor` is not transparent. So we can reduce the number of rendered widgets by half. 
And please note that `ListView.builder` and `ListView` are completely disparate in the way they render widgets. `ListView.builder` renders only "visible" widgets instead of rendering all the widgets like `ListView`.
And yes, this PR should be declined! 😥

**Comment by umechanhika** [comment]
@princ3od 
Thank you for your reply!
I'm sorry, the reply has become long.

> Actually, I used the package wrong to show a normal line. Silly me.
> But like when you set dashLength to a very small value (below 1 for example), it may cause lag. Because the number of dash is countless, and also be double since we render dashGap too.

I thought that the idea of ​​drawing a single line using Container when dashGapLength = 0 or dashGapColor = transparent is good!
But, as you write, this usage isn't supposed in my package.
If you want to draw a straight line, it's better to use Container instead of this package.

> I suggest that we only render dash when dashGapColor is transparent, and only render 1 dash line with many dashGap when dashGapColor is not transparent. So we can reduce the number of rendered widgets by half.

The large number of widgets drawn is a fundamental issue for this package to solve.
However, I think it is a different issue from your proposal, so it is not preferable to discuss it in this PR. (The problem with the number of widgets drawn will occur even if dashLength = 0 is not the case.)
If you have a solution to this, I would be very happy if you could make another PR!

> And please note that ListView.builder and ListView are completely disparate in the way they render widgets. ListView.builder renders only "visible" widgets instead of rendering all the widgets like ListView.

I also know the difference between `ListView` and` ListView.builder`, and older versions used `ListView.builder`.
However, all widgets drawn by this package will be displayed as `visible` on the screen. Because dotted_line is not a scrolling list.
Therefore, the advantage of `ListView.builder` that only` visible` wighets are drawn on the screen was not taken advantage of:cry:

Finally
Sorry for the long reply.
Your proposal this time is not accepted.
But don't forget, I was very pleased with your suggestion!
I hope that you will continue to use and contribute to this package.

**Pull request closed without merging**
