### PR TITLE
null-safety (minimal) changes

### PR DESCRIPTION
**Pull request by amitkot**
@umechanhika please review

### CODE REVIEW

**Comment by amitkot** [comment]
Solves #28

**Comment by umechanhika** [comment]
Thank you for your contribution.
#27 was submitted earlier, so maybe I'll adopt it.
I'm sorry in that case.

**Comment by amitkot** [comment]
Oh, I missed it! 
Sure, no problem. There was very little effort involved in this PR as basically the only change is the widget's Key which should now be explicitly nullable. 

Thanks for developing and maintaining this package!

**Comment by umechanhika** [comment]
@amitkot 
I have finally merged #27 , so I close this PR.
Thank you very much for taking the time for this package!

**Pull request closed without merging**
